version: '3.9'
services:
    selenium:
        container_name: selenium
        image: selenium/standalone-chrome
        restart: always
        expose:
          - '4444'
        ports:
          - '4444:4444'
          - '7900:7900'
        shm_size: 2g
    TiktokToDiscord:
        container_name: tiktodis
        build: .
        image: tiktodis
        restart: on-failure
        env_file: .env
        depends_on:
          - selenium